"""add flakiness table

Revision ID: 9659035aafbe
Revises: add_clusters_and_failure_columns
Create Date: 2025-11-22 20:17:33.608877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9659035aafbe'
down_revision: Union[str, Sequence[str], None] = 'add_clusters_and_failure_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flakiness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('flakiness_score', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flakiness_id'), 'flakiness', ['id'], unique=False)
    op.create_index(op.f('ix_flakiness_job_name'), 'flakiness', ['job_name'], unique=False)
    op.create_index(op.f('ix_flakiness_test_name'), 'flakiness', ['test_name'], unique=False)
    op.alter_column('clusters', 'member_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('clusters', 'cluster_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_clusters_id'), 'clusters', ['id'], unique=False)
    op.drop_constraint(op.f('fk_failures_cluster_id'), 'failures', type_='foreignkey')
    op.create_foreign_key(None, 'failures', 'clusters', ['cluster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'failures', type_='foreignkey')
    op.create_foreign_key(op.f('fk_failures_cluster_id'), 'failures', 'clusters', ['cluster_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_clusters_id'), table_name='clusters')
    op.alter_column('clusters', 'cluster_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('clusters', 'member_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_flakiness_test_name'), table_name='flakiness')
    op.drop_index(op.f('ix_flakiness_job_name'), table_name='flakiness')
    op.drop_index(op.f('ix_flakiness_id'), table_name='flakiness')
    op.drop_table('flakiness')
    # ### end Alembic commands ###
