"""add cluster trends table

Revision ID: d6b286db3449
Revises: 9659035aafbe
Create Date: 2025-11-23 06:38:50.842333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b286db3449'
down_revision = '9659035aafbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('moving_avg_7d', sa.Float(), nullable=True),
    sa.Column('moving_avg_30d', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('spike_flag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_trends_id'), 'cluster_trends', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cluster_trends_id'), table_name='cluster_trends')
    op.drop_table('cluster_trends')
    # ### end Alembic commands ###
